// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Feb  9 21:15:48 2007

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MAINWINDOW_H
#define MAINWINDOW_H


class MainWindow: public wxFrame {
public:
    // begin wxGlade: MainWindow::ids
    // end wxGlade

    MainWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainWindow::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MainWindow::attributes
    wxStaticText* label_4;
    wxStaticText* label_5;
    wxTextCtrl* text_ctrl_2;
    wxStaticText* label_6;
    wxTextCtrl* text_ctrl_3;
    wxButton* button_8;
    wxStaticText* label_3;
    wxTextCtrl* text_ctrl_4;
    wxButton* Download;
    wxStaticText* label_7;
    wxComboBox* combo_box_1;
    wxStaticText* label_8;
    wxTextCtrl* text_ctrl_5;
    wxButton* button_4;
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_6;
    wxButton* button_5;
    wxButton* button_6;
    wxButton* button_7;
    wxStaticText* label_2;
    // end wxGlade
}; // wxGlade: end class


#endif // MAINWINDOW_H
