// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Feb  9 19:49:13 2007

#include "mainwindow.h"


MainWindow::MainWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MainWindow::MainWindow
    panel_1 = new wxPanel(this, -1, wxDefaultPosition, wxDefaultSize, wxSTATIC_BORDER|wxTAB_TRAVERSAL);
    bitmap_1 = new wxStaticBitmap(panel_1, -1, wxBitmap(wxT("/home/bene/projects/usbprog/trunk/usbprog_online/images/usbprog.jpg"), wxBITMAP_TYPE_ANY));
    label_1 = new wxStaticText(panel_1, -1, wxT("Created by Benedikt Sauter (sauter@ixbat.de)  \nhttp://www.embedded-projects.net/usbprog"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MainWindow::set_properties()
{
    // begin wxGlade: MainWindow::set_properties
    SetTitle(wxT("usbprog Online"));
    SetSize(wxSize(563, 293));
    // end wxGlade
}


void MainWindow::do_layout()
{
    // begin wxGlade: MainWindow::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    sizer_4->Add(bitmap_1, 0, wxADJUST_MINSIZE, 0);
    sizer_3->Add(sizer_4, 1, wxEXPAND, 0);
    sizer_3->Add(label_1, 0, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
    panel_1->SetAutoLayout(true);
    panel_1->SetSizer(sizer_3);
    sizer_3->Fit(panel_1);
    sizer_3->SetSizeHints(panel_1);
    sizer_2->Add(panel_1, 1, wxEXPAND, 0);
    sizer_1->Add(sizer_2, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

