// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Feb  9 20:22:44 2007

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MAINWINDOW_H
#define MAINWINDOW_H


class MainWindow: public wxFrame {
public:
    // begin wxGlade: MainWindow::ids
    // end wxGlade

    MainWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainWindow::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MainWindow::attributes
    wxStaticBox* sizer_1_staticbox;
    wxStaticText* footer;
    // end wxGlade
}; // wxGlade: end class


#endif // MAINWINDOW_H
