// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Nov 17 09:27:20 2006

#include "main.h"


MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    static_line_1 = new wxStaticLine(this, -1);
    panel_1 = new wxPanel(this, -1);
    frame_1_statusbar = CreateStatusBar(1, 0);
    menubar = new wxMenuBar();
    SetMenuBar(menubar);
    wxMenu* File = new wxMenu();
    File->Append(wxNewId(), wxT("About"), wxT(""), wxITEM_NORMAL);
    menubar->Append(File, wxT("File"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("avrupdate - Easy Online Update"));
    int frame_1_statusbar_widths[] = { -1 };
    frame_1_statusbar->SetStatusWidths(1, frame_1_statusbar_widths);
    const wxString frame_1_statusbar_fields[] = {
        wxT("frame_1_statusbar")
    };
    for(int i = 0; i < frame_1_statusbar->GetFieldsCount(); ++i) {
        frame_1_statusbar->SetStatusText(frame_1_statusbar_fields[i], i);
    }
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(static_line_1, 0, wxEXPAND, 0);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}



class avrupdate: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(avrupdate)

bool avrupdate::OnInit()
{
    wxInitAllImageHandlers();
    MyFrame* frame_1 = new MyFrame(0, -1, wxT(""));
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
}






