// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Nov 17 09:27:20 2006

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef MAIN_H
#define MAIN_H


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxMenuBar* menubar;
    wxStatusBar* frame_1_statusbar;
    wxStaticLine* static_line_1;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // MAIN_H
