/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *hbox1;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *vbox3;
  GtkWidget *vbox6;
  GtkWidget *hbox12;
  GtkWidget *label25;
  GtkWidget *hbox11;
  GtkWidget *hbox19;
  GtkWidget *label28;
  GtkWidget *entry3;
  GtkWidget *label29;
  GtkWidget *entry4;
  GtkWidget *hbox16;
  GtkWidget *hseparator3;
  GtkWidget *hbox13;
  GtkWidget *label30;
  GtkWidget *entry2;
  GtkWidget *hbox15;
  GtkWidget *hseparator2;
  GtkWidget *hbox10;
  GtkWidget *label18;
  GtkWidget *fixed1;
  GtkWidget *label21;
  GtkWidget *label23;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label22;
  GtkWidget *label24;
  GtkWidget *hbox14;
  GtkWidget *hseparator1;
  GtkWidget *vbuttonbox2;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *hbox17;
  GtkWidget *hseparator4;
  GtkWidget *hbox18;
  GtkWidget *label27;
  GtkWidget *label1;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *vbox2;
  GtkWidget *hbox4;
  GtkWidget *label15;
  GtkWidget *hbox2;
  GtkWidget *scrolledwindow4;
  GtkWidget *iconview1;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview1;
  GtkWidget *hbox7;
  GtkWidget *label16;
  GtkWidget *scrolledwindow5;
  GtkWidget *textview2;
  GtkWidget *hbox8;
  GtkWidget *label17;
  GtkWidget *hbox3;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *label3;

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window), _("avrupdate - AVR Online Update"));
  gtk_window_set_position (GTK_WINDOW (window), GTK_WIN_POS_CENTER);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (window), hbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 3);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_OUT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 10, 10, 10, 10);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox3);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox6, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox12, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("<b>USB:</b>"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox11, TRUE, TRUE, 0);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (hbox11), hbox19, TRUE, TRUE, 0);

  label28 = gtk_label_new (_("Vendor ID: "));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox19), label28, FALSE, FALSE, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (hbox19), entry3, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry3, 40, -1);

  label29 = gtk_label_new (_("       Product ID: "));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox19), label29, FALSE, FALSE, 0);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (hbox19), entry4, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry4, 40, -1);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox16, TRUE, TRUE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (hbox16), hseparator3, TRUE, TRUE, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox13, FALSE, TRUE, 0);

  label30 = gtk_label_new (_("<b>Version File</b> (http://www../version.conf)<b>:</b>"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox13), label30, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_box_pack_start (GTK_BOX (vbox6), entry2, FALSE, FALSE, 0);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox15, TRUE, TRUE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (hbox15), hseparator2, TRUE, TRUE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox10, FALSE, TRUE, 0);

  label18 = gtk_label_new (_("<b>Application Info:</b>"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox10), label18, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (vbox6), fixed1, TRUE, TRUE, 0);

  label21 = gtk_label_new (_("Title:"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed1), label21, 32, 24);
  gtk_widget_set_size_request (label21, 48, 17);

  label23 = gtk_label_new (_("21234 Byte"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed1), label23, 88, 40);
  gtk_widget_set_size_request (label23, 112, 16);

  label20 = gtk_label_new (_("Size:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed1), label20, 24, 40);
  gtk_widget_set_size_request (label20, 62, 16);

  label19 = gtk_label_new (_("Version:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed1), label19, 32, 56);
  gtk_widget_set_size_request (label19, 72, 16);

  label22 = gtk_label_new (_("usbprog"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed1), label22, 88, 24);
  gtk_widget_set_size_request (label22, 88, 17);

  label24 = gtk_label_new (_("9"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed1), label24, 88, 56);
  gtk_widget_set_size_request (label24, 46, 17);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox14, TRUE, TRUE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (hbox14), hseparator1, TRUE, TRUE, 0);

  vbuttonbox2 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox6), vbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox2), GTK_BUTTONBOX_SPREAD);

  button9 = gtk_button_new_with_mnemonic (_("Read AVR Version"));
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  button10 = gtk_button_new_with_mnemonic (_("Quick Auto Update"));
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), button10);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox17, TRUE, TRUE, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (hbox17), hseparator4, TRUE, TRUE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox18, TRUE, TRUE, 0);

  label27 = gtk_label_new (_("Author: Benedik Sauter <sauter@ixbat.de>\nHomepage: http://www.ixbat.de"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox18), label27, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("AVR Board"));
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox1), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 3);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_OUT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 10, 10, 10, 10);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), vbox2);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, FALSE, TRUE, 0);

  label15 = gtk_label_new (_("<b>Online:</b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  hbox2 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, TRUE, TRUE, 1);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox2), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  iconview1 = gtk_icon_view_new ();
  gtk_widget_show (iconview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), iconview1);
  gtk_icon_view_set_orientation (GTK_ICON_VIEW (iconview1), GTK_ORIENTATION_HORIZONTAL);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (hbox2), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview1);
  gtk_widget_set_size_request (textview1, 145, 170);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox7, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("<b>Log:</b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox7), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), textview2);
  gtk_widget_set_size_request (textview2, -1, 116);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox8, TRUE, TRUE, 0);

  label17 = gtk_label_new (_("<b>Process:</b>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, FALSE, TRUE, 0);

  button6 = gtk_button_new_with_mnemonic (_("Download Version List"));
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox3), button6, FALSE, FALSE, 0);

  button7 = gtk_button_new_with_mnemonic (_("Flash selected File"));
  gtk_widget_show (button7);
  gtk_box_pack_start (GTK_BOX (hbox3), button7, FALSE, FALSE, 0);

  button8 = gtk_button_new_with_mnemonic (_("Start Application"));
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (hbox3), button8, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Online Versions"));
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label3);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window, label25, "label25");
  GLADE_HOOKUP_OBJECT (window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window, label28, "label28");
  GLADE_HOOKUP_OBJECT (window, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window, label29, "label29");
  GLADE_HOOKUP_OBJECT (window, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window, label30, "label30");
  GLADE_HOOKUP_OBJECT (window, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window, label18, "label18");
  GLADE_HOOKUP_OBJECT (window, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window, label21, "label21");
  GLADE_HOOKUP_OBJECT (window, label23, "label23");
  GLADE_HOOKUP_OBJECT (window, label20, "label20");
  GLADE_HOOKUP_OBJECT (window, label19, "label19");
  GLADE_HOOKUP_OBJECT (window, label22, "label22");
  GLADE_HOOKUP_OBJECT (window, label24, "label24");
  GLADE_HOOKUP_OBJECT (window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window, vbuttonbox2, "vbuttonbox2");
  GLADE_HOOKUP_OBJECT (window, button9, "button9");
  GLADE_HOOKUP_OBJECT (window, button10, "button10");
  GLADE_HOOKUP_OBJECT (window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window, label27, "label27");
  GLADE_HOOKUP_OBJECT (window, label1, "label1");
  GLADE_HOOKUP_OBJECT (window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window, label15, "label15");
  GLADE_HOOKUP_OBJECT (window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window, iconview1, "iconview1");
  GLADE_HOOKUP_OBJECT (window, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window, label16, "label16");
  GLADE_HOOKUP_OBJECT (window, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window, label17, "label17");
  GLADE_HOOKUP_OBJECT (window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window, button6, "button6");
  GLADE_HOOKUP_OBJECT (window, button7, "button7");
  GLADE_HOOKUP_OBJECT (window, button8, "button8");
  GLADE_HOOKUP_OBJECT (window, label3, "label3");

  return window;
}

