/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class simpleportJNI {
  public final static native long simpleport_open();
  public final static native void simpleport_close(long jarg1);
  public final static native short simpleport_message(long jarg1, String jarg2, int jarg3);
  public final static native void simpleport_set_direction(long jarg1, short jarg2);
  public final static native void simpleport_set_port(long jarg1, short jarg2, short jarg3);
  public final static native short simpleport_get_port(long jarg1);
  public final static native void simpleport_set_pin_dir(long jarg1, int jarg2, int jarg3);
  public final static native void simpleport_set_pin(long jarg1, int jarg2, int jarg3);
  public final static native int simpleport_get_pin(long jarg1, int jarg2);
}
