/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "simpleport.h"
#include <usb.h>
#define VID 0x1781
#define PID 0x0c62

#define UNKOWN_COMMAND  0x00
#define PORT_DIRECTION  0x01
#define PORT_SET        0x02
#define PORT_GET        0x03
#define PORT_SETBIT     0x04
#define PORT_GETBIT     0x05

extern struct simpleport* simpleport_open();
extern void simpleport_close(struct simpleport *);
extern unsigned char simpleport_message(struct simpleport *, char *, int );
extern void simpleport_set_direction(struct simpleport *, unsigned char );
extern void simpleport_set_port(struct simpleport *,unsigned char , unsigned char );
extern unsigned char simpleport_get_port(struct simpleport *);
extern void simpleport_set_pin_dir(struct simpleport *,int , int );
extern void simpleport_set_pin(struct simpleport *,int , int );
extern int simpleport_get_pin(struct simpleport *, int );


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_simpleportJNI_simpleport_1open(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct simpleport *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct simpleport *)simpleport_open();
  *(struct simpleport **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_simpleportJNI_simpleport_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  simpleport_close(arg1);
}


SWIGEXPORT jshort JNICALL Java_simpleportJNI_simpleport_1message(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jshort jresult = 0 ;
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (unsigned char)simpleport_message(arg1,arg2,arg3);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_simpleportJNI_simpleport_1set_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2) {
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  simpleport_set_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_simpleportJNI_simpleport_1set_1port(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3) {
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  unsigned char arg2 ;
  unsigned char arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  arg3 = (unsigned char)jarg3; 
  simpleport_set_port(arg1,arg2,arg3);
}


SWIGEXPORT jshort JNICALL Java_simpleportJNI_simpleport_1get_1port(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  result = (unsigned char)simpleport_get_port(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_simpleportJNI_simpleport_1set_1pin_1dir(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  simpleport_set_pin_dir(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_simpleportJNI_simpleport_1set_1pin(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  simpleport_set_pin(arg1,arg2,arg3);
}


SWIGEXPORT jint JNICALL Java_simpleportJNI_simpleport_1get_1pin(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  struct simpleport *arg1 = (struct simpleport *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct simpleport **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)simpleport_get_pin(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

