/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class simpleport {
  public static SWIGTYPE_p_simpleport simpleport_open() {
    long cPtr = simpleportJNI.simpleport_open();
    return (cPtr == 0) ? null : new SWIGTYPE_p_simpleport(cPtr, false);
  }

  public static void simpleport_close(SWIGTYPE_p_simpleport arg0) {
    simpleportJNI.simpleport_close(SWIGTYPE_p_simpleport.getCPtr(arg0));
  }

  public static short simpleport_message(SWIGTYPE_p_simpleport arg0, String arg1, int arg2) {
    return simpleportJNI.simpleport_message(SWIGTYPE_p_simpleport.getCPtr(arg0), arg1, arg2);
  }

  public static void simpleport_set_direction(SWIGTYPE_p_simpleport arg0, short arg1) {
    simpleportJNI.simpleport_set_direction(SWIGTYPE_p_simpleport.getCPtr(arg0), arg1);
  }

  public static void simpleport_set_port(SWIGTYPE_p_simpleport arg0, short arg1, short arg2) {
    simpleportJNI.simpleport_set_port(SWIGTYPE_p_simpleport.getCPtr(arg0), arg1, arg2);
  }

  public static short simpleport_get_port(SWIGTYPE_p_simpleport arg0) {
    return simpleportJNI.simpleport_get_port(SWIGTYPE_p_simpleport.getCPtr(arg0));
  }

  public static void simpleport_set_pin_dir(SWIGTYPE_p_simpleport arg0, int arg1, int arg2) {
    simpleportJNI.simpleport_set_pin_dir(SWIGTYPE_p_simpleport.getCPtr(arg0), arg1, arg2);
  }

  public static void simpleport_set_pin(SWIGTYPE_p_simpleport arg0, int arg1, int arg2) {
    simpleportJNI.simpleport_set_pin(SWIGTYPE_p_simpleport.getCPtr(arg0), arg1, arg2);
  }

  public static int simpleport_get_pin(SWIGTYPE_p_simpleport arg0, int arg1) {
    return simpleportJNI.simpleport_get_pin(SWIGTYPE_p_simpleport.getCPtr(arg0), arg1);
  }

}
